GPUS: '0'
DATA_DIR: ''
OUTPUT_DIR: 'output'
LOG_DIR: 'log'
WORKERS: 4
PRINT_FREQ: 10

DATASET:
  DATASET: 'lumbar'
  ROOT: '../../data'
  TEST_SET: 'DatasetA/test'
  TRAIN_SET: 'DatasetB/train'
  FLIP: true
  ROT_FACTOR: 40
  SCALE_FACTOR: 0.3
MODEL:
  NAME: 'lp_net'
  INIT_WEIGHTS: False
  IMAGE_SIZE:
  - 512
  - 512
  NUM_JOINTS: 11
  EXTRA:
    USE_GCB: false
    TARGET_TYPE: 'gaussian'
    HEATMAP_SIZE:
    - 128
    - 128
    SIGMA: 2
    FINAL_CONV_KERNEL: 1
    DECONV_WITH_BIAS: false
    NUM_DECONV_LAYERS: 2
    NUM_DECONV_FILTERS:
    - 256
    - 256
    NUM_DECONV_KERNELS:
    - 4
    - 4
    NUM_LAYERS: 101
LOSS:
  USE_TARGET_WEIGHT: true
TRAIN:
  BATCH_SIZE: 6
  SHUFFLE: true
  BEGIN_EPOCH: 0
  END_EPOCH: 360
  RESUME: True
  OPTIMIZER: 'adam'
  LR: 0.001
  LR_FACTOR: 0.1
  LR_STEP:
  - 90
  - 120
  WD: 0.0001
  GAMMA1: 0.99
  GAMMA2: 0.0
  MOMENTUM: 0.9
  NESTEROV: false
TEST:
  BATCH_SIZE: 6
  BBOX_THRE: 1.0
  FLIP_TEST: false
  IMAGE_THRE: 0.0
  IN_VIS_THRE: 0.2
  MODEL_FILE: ''
  NMS_THRE: 1.0
  OKS_THRE: 0.9
  USE_GT_BBOX: false
DEBUG:
  DEBUG: true
  SAVE_BATCH_IMAGES_GT: true
  SAVE_BATCH_IMAGES_PRED: true
  SAVE_HEATMAPS_GT: true
  SAVE_HEATMAPS_PRED: true
